#!/usr/bin/env bash
# decisions-digest.sh — Generate a file of recent decisions and rules for CC to read.
# Zero token cost. Reads from Chartroom, writes to a file in CC's read path.
# Run: at session start, or via cron daily.

set -uo pipefail

OUTPUT="/root/.openclaw/DECISIONS.md"
TEMP="/tmp/decisions-digest-staging.md"

cat > "$TEMP" << 'HEADER'
# Active Decisions & Rules (auto-generated from Chartroom)
<!-- Read this at session start. These are decisions made in previous sessions. -->
<!-- Do NOT edit — regenerated by decisions-digest.sh from chart data. -->

HEADER

# Helper: parse chart search output (score+category+id line, then indented text line)
parse_charts() {
  local SEARCH="$1"
  chart search "$SEARCH" 2>/dev/null | while IFS= read -r line; do
    # Score line: "0.59  reading       decision-subtask-tracking..."
    if [[ "$line" =~ ^[0-9] ]]; then
      CHART_ID=$(echo "$line" | awk '{print $NF}')
    # Text line: "    Robert approved subtask model..."
    elif [[ "$line" =~ ^[[:space:]] ]] && [ -n "${CHART_ID:-}" ]; then
      TEXT=$(echo "$line" | sed 's/^[[:space:]]*//' | head -c 300)
      echo "- **${CHART_ID}**: ${TEXT}"
      CHART_ID=""
    fi
  done
}

echo "## Recent Decisions" >> "$TEMP"
echo "" >> "$TEMP"
parse_charts "decision" >> "$TEMP"
echo "" >> "$TEMP"

echo "## Open Issues" >> "$TEMP"
echo "" >> "$TEMP"
parse_charts "issue" >> "$TEMP"
echo "" >> "$TEMP"

echo "## Key Patterns" >> "$TEMP"
echo "" >> "$TEMP"
parse_charts "reading" | head -40 >> "$TEMP"
echo "" >> "$TEMP"

echo "---" >> "$TEMP"
echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$TEMP"

cp "$TEMP" "$OUTPUT"
rm -f "$TEMP"

echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) decisions-digest generated ($(wc -l < "$OUTPUT") lines)"
